# Generated by Django 4.2.9 on 2024-02-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_my_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
